server:
  applicationConnectors:
    - type: http
      port: 9000

  adminConnectors:
    - type: http
      port: 9001


database:
  driverClass: com.mysql.jdbc.Driver
  user: javaeeeee
  password: 1
  url: jdbc:mysql://localhost:3306/<space>
